all:
	echo "lorem ipsum"

run:
	echo "lorem ipsum"

compile:
	echo "lorem ipsum"

docker:
	docker build -t syntacticanalysis .
	docker tag syntacticanalysis:latest fazenda/syntacticanalysis
	docker push fazenda/syntacticanalysis

zip:
	echo "lorem ipsum"
